### ISSUE TITLE
typo in my email address at https://dice-research.org/MuhammadSaleem

### ISSUE THREAD

**Issue by saleem-muhammad** [dice-group/dice-website#130]
the correct email address is 
saleem@informatik.uni-leipzig.de. Could you please update it. thanks

**Comment by yamalight** [comment]
@saleem-muhammad you can update it here youself - just edit [your file here](https://github.com/dice-group/dice-website/blob/develop/data/people/MuhammadSaleem.ttl)

**Comment by saleem-muhammad** [comment]
ohh thanks.
