### ISSUE TITLE
encoding glitch

### ISSUE THREAD

**Issue by bigerl** [dice-group/dice-website#140]
![image](https://user-images.githubusercontent.com/933146/69612975-0a45a600-1031-11ea-880c-147cebde3853.png)
at https://dice-research.org/publications/

**Comment by yamalight** [comment]
That seems to be a problem with our bib file, it has the same issue on bibsonomy.org (and there's two of them):
![image](https://user-images.githubusercontent.com/365944/69618308-fa7e8f80-1039-11ea-9b1f-9c30e6caa13f.png)

**Comment by yamalight** [comment]
Closing this since it's not website-related
