### ISSUE TITLE
Automatic deployment does not seem to work, anymore

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/dice-website#165]
## Problem description

We merged https://github.com/dice-group/dice-website/pull/159 6 days ago. One of the changes is the page of the GERBIL project that should look like this: https://deploy-preview-159--dice-website-preview.netlify.com/GERBIL

However, the page of GERBIL is still (nearly) without any content: https://dice-research.org/GERBIL 

Shouldn't the website be deployed automatically? Maybe the deployment is still configured for the master branch and not for develop? :thinking:

**Comment by yamalight** [comment]
@MichaelRoeder you need to merge whatever you want to deploy to `master`. See [wiki](https://github.com/dice-group/dice-website/wiki/How-to-deploy%3F) for more details.

**Comment by MichaelRoeder** [comment]
Why is the default branch `develop` if we need to merge to master? :open_mouth:

**Comment by yamalight** [comment]
@MichaelRoeder `master` is protected and can only be used via PRs. it's convenient when you can just clone a repo and start working on it (or create a file from github without jumping through branches), and - as a bonus - people won't commit / push broken stuff into deployment branch by default.

**Comment by MichaelRoeder** [comment]
Got it. Thanks.
