### ISSUE TITLE
Usage of anchors could be helpful

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/dice-website#194]
## User Story

As an author of a web page, I would like to structure my page to make it readable and easy to access. Especially on larger pages (https://dice-research.org/thesesinfo/ but also https://dice-research.org/jobs/), it can be helpful to start with a short table of contents (TOC) to allow people to jump to the part of the page they are interested in. However, the manual creation of such a table is not supported since the framework does not create an anchor for each headline. Would it be possible to add an `id` to the headline to be able to reference it as link?

## Suggestion

```markdown
## My headline
```
could be translated to 
```HTML
<h2 id="My-headline">My headline</h2>
```
Based on that, the following <a href="#My-headline">link</a> could be formed to reference the headline below:
<h2 id="My-headline">My headline</h2>

**Comment by yamalight** [comment]
Done, (after new deploy) you can use `#heading-name` (replace spaces with `-` and lowercase) to reference headers anywhere in markdown, e.g.:
```md
# My header

...

## Other part

See [my header above](#my-header)
