### ISSUE TITLE
Team persons pages

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#215]
The persons pages have to updated.

The data for persons is here: https://github.com/dice-group/dice-website/tree/develop/data/people. You can **edit it directly**.

If you do not want to edit the data directly, **add a comment in this issue**, e.g.  

> PersonA has mail persona@mail.cs.upb.de

or

> Person A should be in the list of students

**Comment by adibaba** [comment]
I added (only name entries, no mail etc):

- Hardik
- Melissa

**Comment by MichaelRoeder** [comment]
1. Moved Zafar to Alumni
2. We have the example person on our page. The build process should typically remove this file before building the page:

![Team   DICE Research Group](https://user-images.githubusercontent.com/6122307/80235009-5ab14600-8659-11ea-8ab1-57fd36cc5c70.png)

**Comment by adibaba** [comment]
Closing, as there were no additional requests
