### ISSUE TITLE
Adding Theses

### ISSUE THREAD

**Issue by Demirrr** [dice-group/dice-website#280]
Hello all,

I would like to add a new batchelor thesis topic into our page. Consequently, I have pushed the following [RobostEmbeddings.mdx file](https://github.com/dice-group/dice-website/blob/develop/pages/theses/RobostEmbeddings.mdx). Following, I could not find this new topics in [our page](https://dice-research.org/students/theses/). This led me to beleive that I did something wrong :). 

Next, I wanted to understand how gatsby works and wanted to run our website locally. To this end, I executed `../dice-website$ gatsby develop` and obtained the following error
```
gatsby <develop> can only be run for a gatsby site.
Either the current working directory does not contain a valid package.json or
'gatsby' is not specified as a dependency
```
Finally, I stopped and wanted to ask whether we have instructions on how to add a thesis into our page.

**Comment by adibaba** [comment]
Hey Demir,
to run gatsby locally go first into dice-website/scripts/.

https://github.com/dice-group/dice-website/wiki/FAQ

**Comment by adibaba** [comment]
Checked it here locally, the topic is integrated well.

To put it online, you have to merge it into master, you have to

- merge develop into master (by creating a pull request and then merge)
- run the deploy action https://github.com/dice-group/dice-website/actions

**Comment by Demirrr** [comment]
Hello Adrian,

Thanks for the explanation and links. It worked like a charm!
