### ISSUE TITLE
Profile pictures look weird

### ISSUE THREAD

**Issue by Kleanthi** [dice-group/dice-website#39]
The thumbnails and the pictures themselves look weird.

**Comment by yamalight** [comment]
Define "weird" please. If you can - add a screenshot.

**Comment by Kleanthi** [comment]
Example 1
![screenshot1](https://user-images.githubusercontent.com/10223824/65762789-b2b2b900-e119-11e9-8872-45e06df788c9.png)

Example 2
![screenshot2](https://user-images.githubusercontent.com/10223824/65762790-b34b4f80-e119-11e9-9027-f39be5cca420.png)

**Comment by yamalight** [comment]
That is because old pictures are not square. This is exactly why I've asked everyone to update their photos :)

**Comment by Kleanthi** [comment]
Maybe leave the issue open, until all pictures are fixed?

**Comment by yamalight** [comment]
Sure 👍

**Comment by abannoura** [comment]
@yamalight Could you please grant me permission to this repo? I would like to update my photo.

**Comment by yamalight** [comment]
@abannoura if you are in @dice-group - you should already have access to it. 
if not - please request to be added to it.
meanwhile you can fork the repo, update the photo and send a PR with the changes

**Comment by MichaelRoeder** [comment]
I think this should be closed after more than 1 year in which people could fix their own picture :wink:
