### ISSUE TITLE
UPB Colors

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#52]
The official UPB colors could be reused
https://www.uni-paderborn.de/en/university/marketing/design-vorgaben-templates/colors/

The websites of the CS institute typically use, e.g.: (hex) 00205B A93983
https://cs.uni-paderborn.de/

**Comment by yamalight** [comment]
@ngonga do we want to do this? so far we've used colors derived from DICE logo 🤔

**Comment by yamalight** [comment]
Feedback from Axel: We'll be sticking to our colors.
Closing this.
