### ISSUE TITLE
Wiki link in footer

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#53]
Lots of links are in our wiki. On our current/old website there is a link, if someone forgets the URL or for new colleagues.
https://wikis.uni-paderborn.de/dice/

**Comment by yamalight** [comment]
There is a wiki link in the footer 🤔
![image](https://user-images.githubusercontent.com/365944/66115310-da4dc980-e5d0-11e9-95d5-2bbb73bfc8a5.png)

**Comment by adibaba** [comment]
Whops, correct. Link is already there.
