### ISSUE TITLE
Add related links property to projects

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#56]
In some cases, special information is required. That could be non-categorized links or text splitted into multiple paragraphs . For those cases, a rendering of markdown would be nice. Maybe for one special content element, e.g. RDF contents linked with _schema:content_.

**Comment by yamalight** [comment]
@adibaba not sure I understand correctly - could you give an example?

**Comment by adibaba** [comment]
@yamalight 

For paragraphs: At https://dice.codezen.net/OPAL `#Project goal` could become a `<h1>` or `<h2>`.

For links: E.g. for the OPAL project, a link to the related [BMVI page](https://www.bmvi.de/SharedDocs/DE/Artikel/DG/mfund-projekte/ope-data-portal-germany-opal.html) could be added. For other pages, other cases may exist.

**Comment by adibaba** [comment]
For additional links, also a section "Related" with a list of links (URL + title) would work.

**Comment by yamalight** [comment]
@adibaba that should already work actually - `schema:content` _is_ rendered as markdown. I think it's just broken due to formatting (missing space after `#`)

**Comment by yamalight** [comment]
on related links - @ngonga do we want this?
if there's not that many project that have related links - they could just be added inside of that markdown content in `schema:content`

**Comment by adibaba** [comment]
@yamalight thanks for the support! With rendered markdown, this issue may be closed. I'll fix the broken markdown.

**Comment by yamalight** [comment]
@adibaba please leave it open for now as I think related links might be a good addition :)

**Comment by yamalight** [comment]
Feedback from Axel - we don't have links that often, so markdown should be sufficient.
Closing this.
