### ISSUE TITLE
Homepage issues at live system

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#67]
- The link " open-source" points to "https://dice-research.org/demos/", which produces a 404
- Clicking on the "Learn more" button just jumps to "Projects". Maybe remove the button for now? Or change the label, e.g. "View research projects"?
- The blue bullets on the right are jumping while scrolling (the order of bullets is maybe broken)
- The "Funded by" links could open in a new window (target _blank)

**Comment by yamalight** [comment]
1. Fixed the demos link
2. "Learn more" also fits the narrative here, no? 🤔 
3. Can you describe "jumping" a bit more? what exactly happens?
4. Why would this be useful? 🤔

**Comment by adibaba** [comment]
1. Thanks
2. I was confused, as there is no explanation or description of the group. Visitors from outside may be confused, too.
3. If I scroll down, the bullets are darkened in that order: 2, 1, 3, 2, 4, 3, 5, 4, 6, 5
4. Don't loose visitors

**Comment by yamalight** [comment]
2 - got it, will discuss with Axel.
3 - that sounds like a but. what browser are you using? what kind of resolution do you have?
4 - we're not really selling anything, and they still have "back" button 😅

**Comment by adibaba** [comment]
3. Ubuntu Mate (on Desktop and Laptop), both with external monitors. On desktop (currently): 1920x1200. Bug with Chromium, Chrome, and Firefox. 
4. It's more about caring ;) But fine, it's not worth the effort.

**Comment by yamalight** [comment]
Got it, will investigate, thanks
