### ISSUE TITLE
Providing files for download

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#69]
On our former TYPO3 website, I uploaded a PDF for students. Where should we put those files now?

**Comment by yamalight** [comment]
@adibaba I've added `downloads` folder to `./scripts/static/downloads`.
If you put a file in there, it'll be accessible as `https://dice-research.org/downloads/filename.ext`
Please don't put anything very large there though. For cases like this it'd be better to use data/file servers we have.

**Comment by adibaba** [comment]
Good point. What about the Hobbit FTP as a default repository for website downloads?
E.g. https://hobbitdata.informatik.uni-leipzig.de/dice-website/ (created that)

**Comment by yamalight** [comment]
Sounds good to me :)

**Comment by adibaba** [comment]
Added info in the GitHub wiki https://github.com/dice-group/dice-website/wiki/How-to-provide-downloads
