### ISSUE TITLE
Teaching contents

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#70]
Bachelor lectures are not displayed yet

- [L.079.05630 Foundations of the Semantic Web (in English) SoSe 2019](https://paul.upb.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=COURSEDETAILS&ARGUMENTS=-N000000000000002,-N000342,-N0,-N370263289264636,-N370263289237637,-N0,-N0,-N3)
- [L.079.05600 Foundations of the Semantic Web (in English) SoSe 2018](https://paul.upb.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=COURSEDETAILS&ARGUMENTS=-N000000000000002,-N000342,-N0,-N366725630461166,-N366725630483167,-N0,-N0,-N3)

**Comment by yamalight** [comment]
@adibaba there are a few documents from original website that didn't have much content or even metadata, hence they were copied with `.fixit` file extension.
They are not rendered. If you have more info on them - please go through the [list](https://github.com/dice-group/dice-website/tree/develop/pages/teaching), update the `*.fixit` documents and then rename them to `*.mdx`

**Comment by adibaba** [comment]
Updates:

At branch `dev-teaching`, I updated some data of the current semester.
https://github.com/dice-group/dice-website/tree/dev-teaching

The PAUL links could be included by a student researcher. A how-to is in the GitHub wiki.
https://github.com/dice-group/dice-website/wiki/How-to-update-lectures

The files in the list could be renamed to YYYY-SW-TITLE.
SW:=ss|ws

The "TODO" text parts should be deleted. Even an empty page is nicer.

**Comment by MichaelRoeder** [comment]
@adibaba It seems like this issue is fixed, isn't it?

**Comment by adibaba** [comment]
It's a content related issue.
If we want to provide a complete list of courses, some data of the previous semesters is missing.
If we focus on current lectures (e.g. starting at summer term 2020), the data is complete.
https://dice-research.org/students/teaching/
