### ISSUE TITLE
Navigation always happens when project card is clicked

### ISSUE THREAD

**Issue by denkv** [dice-group/dice-website#72]
When I, for example, Control+click a project (which opens it in a new tab in Firefox as it should), the current page navigates to this project as well. It should not.

**Comment by denkv** [comment]
Actually, opening in new tab only works for "Learn more" text, and does not work elsewhere on the project card.

Another related issue: the whole project card has `cursor: pointer`, but is not a link, so does not work without JavaScript, you can't see the address or copy it etc.

**Comment by yamalight** [comment]
That is expected. Do you know how could we make that work without js? 🤔

**Comment by denkv** [comment]
There are several options what we can do with the cursor issue:
* make the whole project card an `<a>` (this may also help with solving the clicking issue)
* remove `cursor: pointer` by default (can be added dynamically if needed)
