### ISSUE TITLE
Jobs (404)

### ISSUE THREAD

**Issue by adibaba** [dice-group/dice-website#80]
3 of 4 job links return 404

**Comment by yamalight** [comment]
Turns out PDFs were hosted on old website. Need to be copied from [here](https://dido.cs.upb.de/projects/jobs-and-positions/)

**Comment by adibaba** [comment]
Turns out that 2 of the URLs are duplicates.
PDFs now available here: https://hobbitdata.informatik.uni-leipzig.de/dice-website/jobs/

**Comment by yamalight** [comment]
Cool, thanks! I'll update the links tomorrow (or if you have time now - PR welcome 😁 )

**Comment by adibaba** [comment]
Maybe we should ask Axel or Arwa for the current state. Or create the old state for now and update it later.

I updated our internal https://wikis.uni-paderborn.de/dice/Website links. (Was not aware of dido.)

Will update website stuff at another time. The semester has started and there are several things to prepare ;)

**Comment by yamalight** [comment]
I've updated the links for now, so I guess this can be closed.
Re-open if needed.
