### ISSUE TITLE
Publication section is not shown in my personal page?

### ISSUE THREAD

**Issue by hamadazahera** [dice-group/dice-website#99]
**Publication** section is not shown in my personal page. Could you please help me to fix it?

**Comment by yamalight** [comment]
Seems like the name you use on the publications doesn't match one on the website.
Easiest solution would be to change the name on the website to one from publications.
Would that be OK for you? 
If not, I'd need to add a bit of code and additional property for linking publications to author.

**Comment by hamadazahera** [comment]
Yes, It is fine. Thanks!

**Comment by yamalight** [comment]
I'll need to debug this. Reopening for now.
